/**
 * Generated by `supabase gen types typescript` (run `npm run db:types`).
 * This file is a hand-written stub used during scaffolding — replace with
 * the generated types as soon as your Supabase project is created.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type JobStatus =
  | "wishlist"
  | "applied"
  | "interview"
  | "offer"
  | "rejected";

export type AIOutputType =
  | "resume"
  | "interview"
  | "cover_letter"
  | "match_score";

export type ReminderType = "interview" | "follow_up" | "deadline";

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          base_resume: string | null;
          ai_provider_pref: "anthropic" | "openai" | null;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["profiles"]["Row"], "created_at"> & {
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["profiles"]["Row"]>;
      };
      jobs: {
        Row: {
          id: string;
          user_id: string;
          company: string;
          role: string;
          description: string | null;
          link: string | null;
          status: JobStatus;
          applied_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["jobs"]["Row"],
          "id" | "created_at" | "updated_at"
        > & { id?: string; created_at?: string; updated_at?: string };
        Update: Partial<Database["public"]["Tables"]["jobs"]["Row"]>;
      };
      ai_outputs: {
        Row: {
          id: string;
          job_id: string;
          user_id: string;
          type: AIOutputType;
          content: Json;
          model: string | null;
          prompt_version: string | null;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["ai_outputs"]["Row"], "id" | "created_at"> & {
          id?: string;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["ai_outputs"]["Row"]>;
      };
      notes: {
        Row: {
          id: string;
          job_id: string;
          user_id: string;
          content: string;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["notes"]["Row"], "id" | "created_at"> & {
          id?: string;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["notes"]["Row"]>;
      };
      reminders: {
        Row: {
          id: string;
          job_id: string;
          user_id: string;
          due_at: string;
          type: ReminderType;
          message: string | null;
          notified_at: string | null;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["reminders"]["Row"], "id" | "created_at"> & {
          id?: string;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["reminders"]["Row"]>;
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      job_status: JobStatus;
      ai_output_type: AIOutputType;
      reminder_type: ReminderType;
    };
  };
}

export type Job = Database["public"]["Tables"]["jobs"]["Row"];
export type Profile = Database["public"]["Tables"]["profiles"]["Row"];
export type AIOutput = Database["public"]["Tables"]["ai_outputs"]["Row"];
export type Note = Database["public"]["Tables"]["notes"]["Row"];
export type Reminder = Database["public"]["Tables"]["reminders"]["Row"];
